name: Run Selenium Script

on:
  schedule:
    - cron: "0 8 * * *"   # Runs every day at 8 AM UTC
  workflow_dispatch:       # Allows manual trigger

jobs:
  selenium:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install selenium requests

      - name: Set up Google Chrome
        uses: browser-actions/setup-chrome@v2
        with:
          chrome-version: stable

      - name: Install ChromeDriver
        run: |
          sudo apt update
          sudo apt install -y chromium-chromedriver
          ln -s /usr/lib/chromium-browser/chromedri
